# Generated by Django 4.2.30 on 2026-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Telegram chat id for personal notifications (from /start deep link).', null=True, unique=True),
        ),
    ]
