# Generated by Django 4.2.30 on 2026-04-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
