# Generated by Django 4.2.30 on 2026-04-22 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=128)),
                ('invoice_number', models.CharField(blank=True, max_length=128)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('defect_type', models.CharField(choices=[('quality', 'Product quality'), ('packaging', 'Packaging'), ('shipping', 'Shipping damage'), ('short', 'Short shipment'), ('expired', 'Expiry / dating'), ('other', 'Other')], default='other', max_length=32)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('quantity_affected', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('damage_description', models.TextField(blank=True)),
                ('suspected_root_cause_customer', models.TextField(blank=True)),
                ('resolution_requested', models.CharField(choices=[('credit', 'Credit'), ('replacement', 'Replacement order'), ('investigation', 'Investigation only'), ('rma', 'Return authorization')], default='investigation', max_length=32)),
                ('estimated_exposure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('zoho_replacement_so_number', models.CharField(blank=True, max_length=64)),
                ('zoho_credit_memo_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='crm.batch')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='crm.customeraccount')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='claims.claim')),
                ('end_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.endcustomer')),
                ('original_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='crm.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='crm.product')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='support.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('authorized_quantity', models.PositiveIntegerField(default=0)),
                ('return_instructions', models.TextField(blank=True)),
                ('status', models.CharField(default='authorized', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rma', to='claims.claim')),
            ],
            options={
                'verbose_name': 'RMA',
                'verbose_name_plural': 'RMAs',
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('finance_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement', to='claims.claim')),
            ],
            options={
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='claims/%Y/%m/')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('packaging', 'Packaging'), ('batch_label', 'Batch label'), ('document', 'Document')], default='image', max_length=32)),
                ('scanned_clean', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='claims.claim')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('replacement_so', 'Replacement sales order'), ('credit_memo', 'Credit memo'), ('reimbursement', 'Reimbursement')], max_length=32)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='claims.claim')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
